### ISSUE TITLE
[chores][melos] understand how to use pubspec_overrides.yaml

### ISSUE THREAD

**Issue by iapicca** [iapicca/yak_packages#225]
temp disabling pubspec_overrides in `melos.yaml` until I know what I'm doing

```yaml
command:
   # ...
    usePubspecOverrides: false
    
```
